version: '3'
services:
  express:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    container_name: express
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm start